### ISSUE TITLE
Method to clear form error ?

### ISSUE THREAD

**Issue by Billybob** [advanced-data-machines/tailwindcss-vue#12]
Hi,
is there a method to erase errors from a form?

**Comment by jgraham44** [comment]
Calling the validate function on the form will clear the form errors if the form groups are valid. If they are not valid then they will remain invalid. The form uses 'async-validator' for validation.

**Comment by Billybob** [comment]
My form is displayed by a show/hide button.
Before cancel the form, I would like to delete all possible error messages (just cosmetic)

**Comment by jgraham44** [comment]
I will see what I can come up with.

**Comment by jgraham44** [comment]
Update to version 1.0.0 and you can now use `this.$refs.form.reset();` to reset your form.

**Comment by Billybob** [comment]
**Thanks !!!**
