### ISSUE TITLE
How to use the components

### ISSUE THREAD

**Issue by pedroobando** [advanced-data-machines/tailwindcss-vue#13]
Hi, Josh. - Greetings from Venezuela

I am trying to use the tv-pagination component, but it has presented a problem.

  <tv-pagination :current="page" :total="pageAll" :perPage="pageSize" buttonSize="sm" @change="changePage">
    </tv-pagination>

I have 2 pages, that is 14 elements, 10 pages each, but do not go to the next page.

Could you please give me a hand. or how to use the component.

Saludos y Gracias. - Thank...!

**Comment by jgraham44** [comment]
Hey there,

The problem I see is you are not using current.sync="page".

```
<tv-pagination :current.sync="page" :total="pageAll" :perPage="pageSize" buttonSize="sm" @change="changePage" />
```

This should allow the patent to update when  `this.$emit('update:current', number);` is triggered.

**Comment by pedroobando** [comment]
Thanks brother. I am using 'tailwind-vue' and I really love it, the work you did

**Comment by pedroobando** [comment]
What difference is there between this.
$ Emit ('change', number); and $ emit ('update: current', number);

**Comment by jgraham44** [comment]
`this.$emit('change', number);` allows you to trigger some action in the parent component with the `@change="something"` - page number as an argument that is passed. `this.$emit('update:current', number);` allows you to sync the reactive property in the parent to the *number* argument value. In this case your *page* property.

**Comment by pedroobando** [comment]
Thanks brother.
