### ISSUE TITLE
modular

### ISSUE THREAD

**Issue by g0shed** [advanced-data-machines/tailwindcss-vue#8]
How about getting this fully modular to load only the components we require and not the full bulk, this would improve load times etc substancially

**Comment by jgraham44** [comment]
@g0shed, thank you for posting an issue! Have you tried importing only the components you want? 

```
import { Button } from '@advanced-data-machines/tailwindcss-vue';
Vue.use(Button);

// or

// only array of components you want
import TailwindcssVue, { Button } from '@advanced-data-machines/tailwindcss-vue';
Vue.use(TailwindcssVue, { components: [Button] });
```
Docs are in the process.

**Comment by g0shed** [comment]
![Annotation 2020-02-24 214154](https://user-images.githubusercontent.com/4745874/75193689-9bbad600-574e-11ea-9935-5e637eb0fed8.jpg)

still imports the whole thing, I tried that before...

**Comment by jgraham44** [comment]
How about the following?
```
import Button from '@advanced-data-machines/tailwindcss-vue/dist/components/button';
Vue.use(Button);
```

**Comment by g0shed** [comment]
I had .22 loaded, now with .24 this has worked indeed, thank you for your help

**Comment by jgraham44** [comment]
No problem! The bundle has been enhanced between the .22 and .24 release.
